### ISSUE TITLE
Deploy to Maven Central via Sonatype OSSRH ?

### ISSUE THREAD

**Issue by bcopy** [semper-reformanda/dependencyversion-maven-plugin#8]
Hello,

I can't seem to find the plugin on Maven central, yet it would be excellent to simplify our workflow with Webjars dependencies.
How about requesting a groupId from Sonatype and deploy the plugin to OSSRH (the Sonatype gateway to Maven central) ?

**Comment by cainj13** [comment]
Hi there @bcopy - glad you found it useful!

Already have it published on central, see [this link](http://search.maven.org/#artifactdetails%7Cio.reformanda.semper%7Cdependencyversion-maven-plugin%7C1.0.1%7Cmaven-plugin).  Alternatively, you could just search for the "io.reformanda.semper" group on [search.maven.org](https://search.maven.org) and you'll have this artifact and its related parent.
